
name: "Test_Build_Release"

on:
  push:
    branches: ["main", "release"]
  
permissions:
  contents: read
  packages: write

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
    
      - name: install pnpm
        run: npm install -g pnpm

      - name: Verify versions
        run: |
          node -v
          npm -v
          pnpm -v

      - name: Install dependencies
        run: pnpm install

      - name: Run tests lint 
        run: pnpm run lint
      
      

