
name: "Test_Build_Release"

on:
  push:
    branches: ["main", "release"]
  
permissions:
  contents: read
  packages: write

jobs:
  test_build_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
    
      - name: install pnpm
        run: npm install -g pnpm
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Verify versions
        run: |
          node -v
          npm -v
          pnpm -v
          cargo --version
          rustc --version

      - name: Install dependencies
        run: pnpm install

      - name: Run tests lint 
        run: pnpm run lint
      
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          libglib2.0-dev \
          libgtk-3-dev \
          libwebkit2gtk-4.1-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev \
          patchelf

      - name: Run tests Clippy
        working-directory: src-tauri
        run: cargo clippy --all-targets --all-features -- -D warnings
      
  publish_release_tauri:
    needs: test_build_release
    permissions:
      contents: write
      packages: write

    runs-on: windows-latest

    env:
      TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
      TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}

    steps:
     - uses: actions/checkout@v4

     - name: setup node
       uses: actions/setup-node@v4
       with:
         node-version: lts/*

     - name: install Rust stable
       uses: dtolnay/rust-toolchain@stable
       with:
        target: x86_64-pc-windows-msvc
    
    
     - name: install pnpm
       run: npm install -g pnpm

     - name: Verify versions
       run: |
         node -v
         npm -v
         pnpm -v
 
     - name: install dependencies frontend
       run: pnpm install

     - uses: tauri-apps/tauri-action@v0.6.2
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         tagName: V0.1.7
         releaseName: "Release V0.1.7"
         releaseBody: "See the changelog for more details."
         releaseDraft: false
         prerelease: false
    

